# Generated by Django 5.2.2 on 2025-06-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='savepost',
            unique_together={('post', 'user')},
        ),
    ]
